# Generated by Django 4.2.2 on 2023-06-08 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_query_registration_visitor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Query",
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
