# Generated by Django 4.2.2 on 2023-06-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_delete_query_delete_registration_delete_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
