# Generated by Django 4.2.2 on 2023-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
