# Generated by Django 4.2.2 on 2023-06-09 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phonenumber",
        ),
    ]
