# Generated by Django 4.2.2 on 2023-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_managers_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
    ]
