# Generated by Django 4.2.2 on 2023-06-10 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_user_phonenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_varified",
            new_name="is_verified",
        ),
    ]
