# Generated by Django 4.2.2 on 2023-06-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_rename_is_varified_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forgot_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
