# Generated by Django 4.2.2 on 2023-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_forgot_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
