# Generated by Django 4.2.2 on 2023-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
