# Generated by Django 4.2.2 on 2023-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
