# Generated by Django 4.2.2 on 2023-06-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
