# Generated by Django 4.2.2 on 2023-06-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=models.EmailField(max_length=255, unique=True),
                max_length=255,
                unique=True,
            ),
        ),
    ]
