# Generated by Django 4.2.2 on 2023-06-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_pendinguser"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="otp",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
