# Generated by Django 4.2.2 on 2023-06-20 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_pendinguser_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
