# Generated by Django 4.2.2 on 2023-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_query"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="location_latitude",
        ),
        migrations.RemoveField(
            model_name="query",
            name="location_longitude",
        ),
        migrations.AddField(
            model_name="query",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
