# Generated by Django 4.2.2 on 2023-06-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_remove_query_location_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="link",
            field=models.CharField(max_length=255),
        ),
    ]
