# Generated by Django 4.2.2 on 2023-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_alter_query_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
